/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iddamalgoda
 */
public class Acc_Control_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Acc_Control_Panel
     */
    Account acc = new Account();

    public Acc_Control_Panel() {
        initComponents();
        acc.setSelectedRadioButtonAtTheBegining(debit, credit, both, none, "receipt");
        acc.setSelectedRadioButtonAtTheBegining(debit1, credit1, both1, none1, "payment");
        acc.setSelectedRadioButtonAtTheBegining(debit2, credit2, both2, none2, "journal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        both = new javax.swing.JRadioButton();
        credit = new javax.swing.JRadioButton();
        debit = new javax.swing.JRadioButton();
        none = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        both1 = new javax.swing.JRadioButton();
        credit1 = new javax.swing.JRadioButton();
        debit1 = new javax.swing.JRadioButton();
        none1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        both2 = new javax.swing.JRadioButton();
        credit2 = new javax.swing.JRadioButton();
        debit2 = new javax.swing.JRadioButton();
        none2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Control Panel");

        jLabel2.setText("Auto fill Receipts Account Code?");

        jLabel3.setText("Auto fill Payments Account Code?");

        jLabel4.setText("Auto fill Journals Account Code?");

        both.setText("Both");
        both.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bothItemStateChanged(evt);
            }
        });
        both.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bothActionPerformed(evt);
            }
        });

        credit.setText("Only Credit A/C Code");
        credit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                creditItemStateChanged(evt);
            }
        });
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });

        debit.setText("Only Debit A/C Code");
        debit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                debitItemStateChanged(evt);
            }
        });
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });

        none.setText("None");
        none.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noneItemStateChanged(evt);
            }
        });
        none.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(debit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credit)
                .addGap(10, 10, 10)
                .addComponent(both)
                .addGap(10, 10, 10)
                .addComponent(none)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debit, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(both, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(none, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        both1.setText("Both");
        both1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                both1ItemStateChanged(evt);
            }
        });
        both1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                both1ActionPerformed(evt);
            }
        });

        credit1.setText("Only Credit A/C Code");
        credit1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                credit1ItemStateChanged(evt);
            }
        });
        credit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credit1ActionPerformed(evt);
            }
        });

        debit1.setText("Only Debit A/C Code");
        debit1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                debit1ItemStateChanged(evt);
            }
        });
        debit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debit1ActionPerformed(evt);
            }
        });

        none1.setText("None");
        none1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                none1ItemStateChanged(evt);
            }
        });
        none1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(debit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credit1)
                .addGap(10, 10, 10)
                .addComponent(both1)
                .addGap(10, 10, 10)
                .addComponent(none1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debit1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(both1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(none1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        both2.setText("Both");
        both2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                both2ItemStateChanged(evt);
            }
        });
        both2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                both2ActionPerformed(evt);
            }
        });

        credit2.setText("Only Credit A/C Code");
        credit2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                credit2ItemStateChanged(evt);
            }
        });
        credit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credit2ActionPerformed(evt);
            }
        });

        debit2.setText("Only Debit A/C Code");
        debit2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                debit2ItemStateChanged(evt);
            }
        });
        debit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debit2ActionPerformed(evt);
            }
        });

        none2.setText("None");
        none2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                none2ItemStateChanged(evt);
            }
        });
        none2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(debit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credit2)
                .addGap(10, 10, 10)
                .addComponent(both2)
                .addGap(10, 10, 10)
                .addComponent(none2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debit2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(both2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(none2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditActionPerformed

    private void bothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bothActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bothActionPerformed

    private void noneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noneActionPerformed

    private void debitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_debitItemStateChanged
        if (debit.isSelected()) {
            credit.setSelected(false);
            both.setSelected(false);
            none.setSelected(false);
        }
    }//GEN-LAST:event_debitItemStateChanged

    private void creditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_creditItemStateChanged
        if (credit.isSelected()) {
            debit.setSelected(false);
            both.setSelected(false);
            none.setSelected(false);
        }
    }//GEN-LAST:event_creditItemStateChanged

    private void bothItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bothItemStateChanged
        if (both.isSelected()) {
            credit.setSelected(false);
            debit.setSelected(false);
            none.setSelected(false);
        }
    }//GEN-LAST:event_bothItemStateChanged

    private void noneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noneItemStateChanged
        if (none.isSelected()) {
            credit.setSelected(false);
            both.setSelected(false);
            debit.setSelected(false);
        }
    }//GEN-LAST:event_noneItemStateChanged

    private void both1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_both1ItemStateChanged
        if (both1.isSelected()) {
            credit1.setSelected(false);
            debit1.setSelected(false);
            none1.setSelected(false);
        }
    }//GEN-LAST:event_both1ItemStateChanged

    private void both1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_both1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_both1ActionPerformed

    private void credit1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_credit1ItemStateChanged
        if (credit1.isSelected()) {
            debit1.setSelected(false);
            both1.setSelected(false);
            none1.setSelected(false);
        }
    }//GEN-LAST:event_credit1ItemStateChanged

    private void credit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credit1ActionPerformed

    private void debit1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_debit1ItemStateChanged
        if (debit1.isSelected()) {
            credit1.setSelected(false);
            both1.setSelected(false);
            none1.setSelected(false);
        }
    }//GEN-LAST:event_debit1ItemStateChanged

    private void debit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debit1ActionPerformed

    private void none1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_none1ItemStateChanged
        if (none1.isSelected()) {
            credit1.setSelected(false);
            debit1.setSelected(false);
            both1.setSelected(false);
        }
    }//GEN-LAST:event_none1ItemStateChanged

    private void none1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_none1ActionPerformed

    private void both2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_both2ItemStateChanged
        if (both2.isSelected()) {
            credit2.setSelected(false);
            debit2.setSelected(false);
            none2.setSelected(false);
        }
    }//GEN-LAST:event_both2ItemStateChanged

    private void both2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_both2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_both2ActionPerformed

    private void credit2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_credit2ItemStateChanged
        if (credit2.isSelected()) {
            debit2.setSelected(false);
            both2.setSelected(false);
            none2.setSelected(false);
        }
    }//GEN-LAST:event_credit2ItemStateChanged

    private void credit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credit2ActionPerformed

    private void debit2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_debit2ItemStateChanged
        if (debit2.isSelected()) {
            credit2.setSelected(false);
            both2.setSelected(false);
            none2.setSelected(false);
        }
    }//GEN-LAST:event_debit2ItemStateChanged

    private void debit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debit2ActionPerformed

    private void none2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_none2ItemStateChanged
        if (none2.isSelected()) {
            credit2.setSelected(false);
            debit2.setSelected(false);
            both2.setSelected(false);
        }
    }//GEN-LAST:event_none2ItemStateChanged

    private void none2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_none2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           acc.setCacheReceipts(debit, credit, both, none);
           acc.setCachePayments(debit1, credit1, both1, none1);
           acc.setCacheJournals(debit2, credit2, both2, none2);
           this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acc_Control_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acc_Control_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acc_Control_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acc_Control_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acc_Control_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton both;
    private javax.swing.JRadioButton both1;
    private javax.swing.JRadioButton both2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton credit;
    private javax.swing.JRadioButton credit1;
    private javax.swing.JRadioButton credit2;
    private javax.swing.JRadioButton debit;
    private javax.swing.JRadioButton debit1;
    private javax.swing.JRadioButton debit2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton none;
    private javax.swing.JRadioButton none1;
    private javax.swing.JRadioButton none2;
    // End of variables declaration//GEN-END:variables
}
