
import java.awt.event.KeyEvent;
import java.sql.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pramo
 */
public class DateChooser_text extends javax.swing.JPanel {

    Date_Handler datehandler = new Date_Handler();

    public int return_index(String month) {
        int index = 0;

        switch (month) {
            case "Jan":
                index = 1;
                break;
            case "Feb":
                index = 2;
                break;
            case "Mar":
                index = 3;
                break;
            case "Apr":
                index = 4;
                break;
            case "May":
                index = 5;
                break;
            case "Jun":
                index = 6;
                break;
            case "Jul":
                index = 7;
                break;
            case "Aug":
                index = 8;
                break;
            case "Sep":
                index = 9;
                break;
            case "Oct":
                index = 10;
                break;
            case "Nov":
                index = 11;
                break;
            case "Dec":
                index = 12;
                break;

        }

        return index;
    }

    public String Return_month(int index) {
        String month = null;

        switch (index) {
            case 1:
                month = "Jan";
                break;
            case 2:
                month = "Feb";
                break;
            case 3:
                month = "Mar";
                break;
            case 4:
                month = "Apr";
                break;
            case 5:
                month = "May";
                break;
            case 6:
                month = "Jun";
                break;
            case 7:
                month = "Jul";
                break;
            case 8:
                month = "Aug";
                break;
            case 9:
                month = "Sep";
                break;
            case 10:
                month = "Oct";
                break;
            case 11:
                month = "Nov";
                break;
            case 12:
                month = "Dec";
                break;

        }

        return month;

    }

    /**
     * Creates new form DateChooser_text
     */
    public DateChooser_text() {
        initComponents();

    }

     public void focus() {
        this.requestFocusInWindow();
        jTextField1.requestFocusInWindow();
     
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jTextField1.setText(datehandler.get_today_day());
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.setText(datehandler.get_today_month());
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTextField3.setText(datehandler.get_today_year());
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
      ///////////////////////////////////////////////////  Days Decrement/////////////////////////////////////////////////////////////////////////////
        
        if (jTextField1.getText().equals("1")) {           // Jumping to 31 and 30 from 1st 
            if (evt.getKeyCode() == KeyEvent.VK_UP) {

                if (jTextField2.getText().equals("Feb") || jTextField2.getText().equals("Apr") || jTextField2.getText().equals("Jun") || jTextField2.getText().equals("Aug") || jTextField2.getText().equals("Sep") || jTextField2.getText().equals("Nov") || jTextField2.getText().equals("Feb")) {
                    jTextField1.setText("31");

                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth - 1));

                } else if (jTextField2.getText().equals("May") || jTextField2.getText().equals("Jul") || jTextField2.getText().equals("Oct") || jTextField2.getText().equals("Dec")) {
                    jTextField1.setText("30");
                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth - 1));

                } else if (jTextField2.getText().equals("Mar")) {     // from march 1st jump to 28th or 29th checking leap years
                    int yr = Integer.parseInt(jTextField3.getText());
                    if (yr % 4 == 0) {
                        if (yr % 100 == 0) {
                            if (yr % 400 == 0) {
                                jTextField1.setText("29"); // Leap Year
                            }
                        }
                        if (yr % 100 == 0) {
                            if (yr % 400 != 0) {
                                jTextField1.setText("28"); // not a leap year
                            }
                        }
                        jTextField1.setText("29");       // leap year

                    }
                    if (yr % 4 != 0) {
                        jTextField1.setText("28");       // not a leap year
                    }
                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth - 1));

                } else if (jTextField2.getText().equals("Jan")) {            // From jan 1st jump to december 31st decrementing year
                    jTextField1.setText("31");

                    int yr = Integer.parseInt(jTextField3.getText());
                    jTextField2.setText("Dec");
                    jTextField3.setText("" + (yr - 1));    // year
                }

            }                                           // /// decrementing normal values 
        } else if (jTextField1.getText().equals("2") || jTextField1.getText().equals("3") || jTextField1.getText().equals("4") || jTextField1.getText().equals("5")
                || jTextField1.getText().equals("6") || jTextField1.getText().equals("7") || jTextField1.getText().equals("8") || jTextField1.getText().equals("9")
                || jTextField1.getText().equals("10") || jTextField1.getText().equals("11") || jTextField1.getText().equals("12") || jTextField1.getText().equals("13") || jTextField1.getText().equals("14")
                || jTextField1.getText().equals("15") || jTextField1.getText().equals("16") || jTextField1.getText().equals("17") || jTextField1.getText().equals("18")
                || jTextField1.getText().equals("19") || jTextField1.getText().equals("20") || jTextField1.getText().equals("21") || jTextField1.getText().equals("22")
                || jTextField1.getText().equals("23") || jTextField1.getText().equals("24") || jTextField1.getText().equals("25") || jTextField1.getText().equals("26")
                || jTextField1.getText().equals("27") || jTextField1.getText().equals("28") || jTextField1.getText().equals("29") || jTextField1.getText().equals("30") || jTextField1.getText().equals("31")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {

                jTextField1.setText("" + (Integer.parseInt(jTextField1.getText()) - 1)); 

            }
        }
/////////////////////////////////////////////////  Days Increment///////////////////////////////////////////////////////////////////////////////////////////////////
        if (jTextField1.getText().equals("30")) {               // from 30th to 1st of next month
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

                if (jTextField2.getText().equals("Apr") || jTextField2.getText().equals("Jun") || jTextField2.getText().equals("Sep") || jTextField2.getText().equals("Nov")) {
                    jTextField1.setText("0");
                    
                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth + 1));

                }
                jTextField1.setText("" + (Integer.parseInt(jTextField1.getText()) + 1));
            }

        } else if (jTextField1.getText().equals("31")) {            // from 31st to 1st of next month
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

                if (jTextField2.getText().equals("Jan") || jTextField2.getText().equals("Mar") || jTextField2.getText().equals("May") || jTextField2.getText().equals("Jul") || jTextField2.getText().equals("Aug") || jTextField2.getText().equals("Oct")) {
                    jTextField1.setText("1");

                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth + 1));

                } else if (jTextField2.getText().equals("Dec")) {      // December to january incrementing the year

                    jTextField1.setText("1");

                    int yr = Integer.parseInt(jTextField3.getText());
                    jTextField2.setText("Jan");
                    jTextField3.setText("" + (yr + 1));
                }
            }

        } else if (jTextField2.getText().equals("Feb")) {                    // for february 
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                if (jTextField1.getText().equals("28")) {                    // at 28 check for leap year 
                    int yr = Integer.parseInt(jTextField3.getText());
                    if (yr % 4 == 0) {
                        if (yr % 100 == 0) {
                            if (yr % 400 == 0) {
                                jTextField1.setText("29"); // Leap Year       // increment to 29
                            }
                        }
                        if (yr % 100 == 0) {
                            if (yr % 400 != 0) {
                                jTextField1.setText("1");
                                int mnth = this.return_index(jTextField2.getText());
                                jTextField2.setText(this.Return_month(mnth + 1));

                                // not a leap year                             // jump to next month
                            }
                        }
                        jTextField1.setText("29");       // leap year             // increment to 29th

                    }
                    if (yr % 4 != 0) {
                        jTextField1.setText("1");
                        int mnth = this.return_index(jTextField2.getText());
                        jTextField2.setText(this.Return_month(mnth + 1));                  // not a leap year
                    }

                } else if (jTextField1.getText().equals("29")) {              // at 29 jump to next month normally
                    jTextField1.setText("1");

                    int mnth = this.return_index(jTextField2.getText());
                    jTextField2.setText(this.Return_month(mnth + 1));
                                                                               // incrementing normal values/////////////////////// for february separately
                } else if (jTextField1.getText().equals("1") || jTextField1.getText().equals("2") || jTextField1.getText().equals("3") || jTextField1.getText().equals("4") || jTextField1.getText().equals("5")
                        || jTextField1.getText().equals("6") || jTextField1.getText().equals("7") || jTextField1.getText().equals("8") || jTextField1.getText().equals("9")
                        || jTextField1.getText().equals("10") || jTextField1.getText().equals("11") || jTextField1.getText().equals("12") || jTextField1.getText().equals("13") || jTextField1.getText().equals("14")
                        || jTextField1.getText().equals("15") || jTextField1.getText().equals("16") || jTextField1.getText().equals("17") || jTextField1.getText().equals("18")
                        || jTextField1.getText().equals("19") || jTextField1.getText().equals("20") || jTextField1.getText().equals("21") || jTextField1.getText().equals("22")
                        || jTextField1.getText().equals("23") || jTextField1.getText().equals("24") || jTextField1.getText().equals("25") || jTextField1.getText().equals("26")
                        || jTextField1.getText().equals("27") || jTextField1.getText().equals("28") || jTextField1.getText().equals("29") || jTextField1.getText().equals("30") || jTextField1.getText().equals("31")) {

                    jTextField1.setText("" + (Integer.parseInt(jTextField1.getText()) + 1));

                }

            }
                                         // incrementing normal values 
        } else if (jTextField1.getText().equals("1") || jTextField1.getText().equals("2") || jTextField1.getText().equals("3") || jTextField1.getText().equals("4") || jTextField1.getText().equals("5")
                || jTextField1.getText().equals("6") || jTextField1.getText().equals("7") || jTextField1.getText().equals("8") || jTextField1.getText().equals("9")
                || jTextField1.getText().equals("10") || jTextField1.getText().equals("11") || jTextField1.getText().equals("12") || jTextField1.getText().equals("13") || jTextField1.getText().equals("14")
                || jTextField1.getText().equals("15") || jTextField1.getText().equals("16") || jTextField1.getText().equals("17") || jTextField1.getText().equals("18")
                || jTextField1.getText().equals("19") || jTextField1.getText().equals("20") || jTextField1.getText().equals("21") || jTextField1.getText().equals("22")
                || jTextField1.getText().equals("23") || jTextField1.getText().equals("24") || jTextField1.getText().equals("25") || jTextField1.getText().equals("26")
                || jTextField1.getText().equals("27") || jTextField1.getText().equals("28") || jTextField1.getText().equals("29") || jTextField1.getText().equals("30") || jTextField1.getText().equals("31")) {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

                jTextField1.setText("" + (Integer.parseInt(jTextField1.getText()) + 1));

            }
        }
         if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
                jTextField2.requestFocus();
            }

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (jTextField2.getText().equals("Jan")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Dec");
                int yr = Integer.parseInt(jTextField3.getText());

                jTextField3.setText("" + (yr - 1));

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Feb");
            }

        } else if (jTextField2.getText().equals("Feb")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Jan");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Mar");
            }

        } else if (jTextField2.getText().equals("Mar")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Feb");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Apr");
            }

        } else if (jTextField2.getText().equals("Apr")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Mar");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("May");
            }

        } else if (jTextField2.getText().equals("May")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Apr");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Jun");
            }

        } else if (jTextField2.getText().equals("Jun")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("May");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Jul");
            }

        } else if (jTextField2.getText().equals("Jul")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Jun");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Aug");
            }

        } else if (jTextField2.getText().equals("Aug")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Jul");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Sep");
            }

        } else if (jTextField2.getText().equals("Sep")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Aug");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Oct");
            }

        } else if (jTextField2.getText().equals("Oct")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Sep");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Nov");
            }

        } else if (jTextField2.getText().equals("Nov")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Oct");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Dec");
            }

        } else if (jTextField2.getText().equals("Dec")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField2.setText("Nov");
                int yr = Integer.parseInt(jTextField3.getText());

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField2.setText("Jan");
                int yr = Integer.parseInt(jTextField3.getText());

                jTextField3.setText("" + (yr + 1));
            }

        }
         if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
                jTextField1.requestFocus();
            }
 if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
                jTextField3.requestFocus();
            }

    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jTextField3.setText("" + (Integer.parseInt(jTextField3.getText()) + 1));
            }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
                jTextField3.setText("" + (Integer.parseInt(jTextField3.getText()) - 1));
            }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
                jTextField2.requestFocus();
            }
    }//GEN-LAST:event_jTextField3KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
