
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pramo
 */
public class PRCR_salary_note_anlysis extends javax.swing.JPanel {

    /**
     * Creates new form PRCR_salary_payroll
     */
    Date_Handler datehandler = new Date_Handler();
    DatabaseManager dbm=DatabaseManager.getDbCon();
    
    //Payroll_Salary spiObject = new Payroll_Salary();
    public PRCR_salary_note_anlysis() {
        initComponents();
    }

    public void setCheckrollTabel(int chk) {
        PRCR_NoteAnalysis a=new PRCR_NoteAnalysis();
        a.Set_year(year.getText());
        a.Set_month(month.getText());
        a.setDivision(division_combo.getSelectedItem().toString());;
        int columnSize = 0;
        //columnSize = a.getColumnsize("pr_workdata_"+a.getString(), "code");
        columnSize=a.checknReturnNumberOfEntriesForNoteAnalysis("pr_workdata_"+a.getString(), "register_or_casual", getReg(register_or_casual_combo.getSelectedItem().toString()), "active","1","code",chk);
        
        System.out.println(columnSize);
        
        double tSalary=0;
        int codes[] = new int[columnSize];
        double salary[] =new double[columnSize];
        ((DefaultTableModel)jTable1.getModel()).setNumRows(columnSize);
        
        //codes = a.getIntArray("pr_workdata_"+a.getString(), "code");
        codes=a.checknReturnIntArrayForNoteAnalysis("pr_workdata_"+a.getString(), "register_or_casual", getReg(register_or_casual_combo.getSelectedItem().toString()),"active","1","code",chk);
        //salary=a.getDoubleArray("pr_workdata_"+a.getString(), "full_salary");
        salary=a.checknReturnDoubleArrayForNoteAnalysis("pr_workdata_"+a.getString(), "register_or_casual", getReg(register_or_casual_combo.getSelectedItem().toString()), "active","1","full_salary",chk);
        for(int i=0;i<columnSize;i++){
            jTable1.setValueAt(codes[i],i, 1);
            jTable1.setValueAt(salary[i], i, 2);
            tSalary=tSalary+salary[i];
        }
        total.setText(Double.toString(tSalary));
                
    }
    public int getReg(String register){//used to get 1 when register is selected and 0 when casual is selected
        if(register=="Register"){
        return 1;
        }else{
        return 0;  //casual
        }
        
    }
     
//
//    public void setStaffTabel() {
//         PRCR_NoteAnalysis a=new PRCR_NoteAnalysis();
//         a.Set_year(year.getText());
//        a.Set_month(month.getText());
//        int columnSize = 0;
//        columnSize = a.getColumnsize("prcr_staffworkdata_"+a.getString(), "code");
//        System.out.println(columnSize);
//        double  tSalary=0;
//        int codes[] = new int[columnSize];
//        double salary[] =new double[columnSize];
//        ((DefaultTableModel)jTable1.getModel()).setNumRows(columnSize);
//       // double arraySal[] = new double[columnSize];
//        codes = a.getIntArray("prcr_staffworkdata_"+a.getString(), "code");
//        salary=a.getDoubleArray("prcr_staffworkdata_"+a.getString(), "full_pay");
//        for(int i=0;i<columnSize;i++){
//            jTable1.setValueAt(codes[i],i, 1);
//            jTable1.setValueAt(salary[i], i, 2);
//            tSalary=tSalary+salary[i];
//            
//        }
//        total.setText(Double.toString(tSalary));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        checkrollOrStaff = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        N5000T = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        fullPay = new javax.swing.JTextField();
        N2000T = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        N1000T = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        N500T = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        N100T = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        N50T = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        N20T = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        N10T = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        basicPay8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        basicPay10 = new javax.swing.JTextField();
        basicPay11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        division = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        register_or_casual_combo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        division_combo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Pay type");

        checkrollOrStaff.setEditable(true);
        checkrollOrStaff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Checkroll", "Staff" }));
        checkrollOrStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkrollOrStaffActionPerformed(evt);
            }
        });
        checkrollOrStaff.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkrollOrStaffFocusLost(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("5000");

        fullPay.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setText("2000");

        jLabel13.setText("1000");

        jLabel14.setText("500");

        jLabel15.setText("100");

        jLabel16.setText("50");

        jLabel17.setText("20");

        jLabel18.setText("10");

        jLabel4.setText("Notes");

        jLabel19.setText("Coins");

        jLabel6.setText("Total");

        basicPay11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicPay11ActionPerformed(evt);
            }
        });

        jLabel20.setText("5");

        jLabel21.setText("2");

        jLabel22.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullPay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(basicPay10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N50T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(N2000T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(N5000T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(N1000T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(N500T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(N100T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N20T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N10T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(basicPay8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(basicPay11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(N5000T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(N2000T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N1000T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N500T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N100T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N50T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N20T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N10T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicPay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicPay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicPay11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Code", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel7.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        month.setText(datehandler.get_today_month());
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthKeyPressed(evt);
            }
        });

        year.setText(datehandler.get_today_year());
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("Month -Year");

        jLabel3.setText("Register or Casual");

        register_or_casual_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Register", "Casual" }));

        jLabel2.setText("Division");

        division_combo.setEditable(true);
        division_combo.setModel(new javax.swing.DefaultComboBoxModel(dbm.getStringArray("division_details", "code")));
        division_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                division_comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout divisionLayout = new javax.swing.GroupLayout(division);
        division.setLayout(divisionLayout);
        divisionLayout.setHorizontalGroup(
            divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(register_or_casual_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(division_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        divisionLayout.setVerticalGroup(
            divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divisionLayout.createSequentialGroup()
                        .addComponent(division_combo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(register_or_casual_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(divisionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(94, 94, 94)
                                .addComponent(checkrollOrStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkrollOrStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(8, 8, 8)
                                .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkrollOrStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkrollOrStaffActionPerformed
//String selection = (String) checkrollOrStaff.getSelectedItem();
//
//        if (selection.equalsIgnoreCase("Staff")) {
//
//            division.setVisible(false);
//            
//
//        }
//
//        if (selection.equalsIgnoreCase("Checkroll")) {
//           division.setVisible(true);
//
//        }        // TODO add your handling code here:

    }//GEN-LAST:event_checkrollOrStaffActionPerformed

    private void checkrollOrStaffFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkrollOrStaffFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_checkrollOrStaffFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (checkrollOrStaff.getSelectedItem() == "Checkroll") {
            PRCR_NoteAnalysis naObject = new PRCR_NoteAnalysis();
          naObject.setDivision(division_combo.getSelectedItem().toString());
            naObject.setReg(register_or_casual_combo.getSelectedItem().toString());
            
            naObject.Set_year(year.getText());
            naObject.Set_month(month.getText());//set the month(ex:2014_03) in the object
            naObject.setNotes(1);//
            N5000T.setText(Integer.toString(naObject.getN5000()));
            N2000T.setText(Integer.toString(naObject.getN2000()));
            N1000T.setText(Integer.toString(naObject.getN1000()));
            N500T.setText(Integer.toString(naObject.getN500()));
            N100T.setText(Integer.toString(naObject.getN100()));
            N50T.setText(Integer.toString(naObject.getN50()));
            N20T.setText(Integer.toString(naObject.getN20()));
            N10T.setText(Integer.toString(naObject.getN10()));
            ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
            setCheckrollTabel(1);
        } else {

              PRCR_NoteAnalysis naObject = new PRCR_NoteAnalysis();
          //naObject.setDivision(division_combo.getSelectedItem().toString());
            naObject.setReg(register_or_casual_combo.getSelectedItem().toString());
            
            naObject.Set_year(year.getText());
            naObject.Set_month(month.getText());//set the month(ex:2014_03) in the object
            naObject.setNotes(2);//
            N5000T.setText(Integer.toString(naObject.getN5000()));
            N2000T.setText(Integer.toString(naObject.getN2000()));
            N1000T.setText(Integer.toString(naObject.getN1000()));
            N500T.setText(Integer.toString(naObject.getN500()));
            N100T.setText(Integer.toString(naObject.getN100()));
            N50T.setText(Integer.toString(naObject.getN50()));
            N20T.setText(Integer.toString(naObject.getN20()));
            N10T.setText(Integer.toString(naObject.getN10()));
            ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
            setCheckrollTabel(2);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void basicPay11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicPay11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicPay11ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void monthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyPressed
        if (month.getText().equals("Jan")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Dec");
                int yr = Integer.parseInt(year.getText());

                year.setText("" + (yr - 1));
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Feb");
                month.selectAll();
            }

        } else if (month.getText().equals("Feb")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Jan");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Mar");
                month.selectAll();
            }

        } else if (month.getText().equals("Mar")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Feb");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();
            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Apr");
                month.selectAll();
            }

        } else if (month.getText().equals("Apr")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Mar");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();
            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("May");
                month.selectAll();
            }

        } else if (month.getText().equals("May")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Apr");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

                month.setText("Jun");
                month.selectAll();
            }

        } else if (month.getText().equals("Jun")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("May");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Jul");
                month.selectAll();
            }

        } else if (month.getText().equals("Jul")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Jun");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Aug");
                month.selectAll();
            }

        } else if (month.getText().equals("Aug")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Jul");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Sep");
                month.selectAll();
            }

        } else if (month.getText().equals("Sep")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Aug");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Oct");
                month.selectAll();
            }

        } else if (month.getText().equals("Oct")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Sep");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Nov");
                month.selectAll();
            }

        } else if (month.getText().equals("Nov")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Oct");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Dec");
                month.selectAll();
            }

        } else if (month.getText().equals("Dec")) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                month.setText("Nov");
                int yr = Integer.parseInt(year.getText());
                month.selectAll();

            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                month.setText("Jan");
                int yr = Integer.parseInt(year.getText());

                year.setText("" + (yr + 1));
                month.selectAll();
            }

        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            //change.requestFocus();
            //change.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            year.requestFocus();
            year.selectAll();
        }
    }//GEN-LAST:event_monthKeyPressed

    private void yearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            year.setText("" + (Integer.parseInt(year.getText()) + 1));
            year.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            year.setText("" + (Integer.parseInt(year.getText()) - 1));
            year.selectAll();
        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            month.requestFocus();
            month.selectAll();
        }
    }//GEN-LAST:event_yearKeyPressed

    private void division_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_division_comboItemStateChanged
        DatabaseManager dbma = DatabaseManager.getDbCon();
        String Name = null;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String item = evt.getItem().toString();

            try {
                ResultSet query = dbma.query("SELECT * FROM division_details WHERE code =" + item + "");
                while (query.next()) {
                    Name = query.getString("division");
                    System.out.println(Name);
                }
            } catch (SQLException ex) {
                System.out.println("error");
            }

            //division_lb.setText("" + Name);
        }
    }//GEN-LAST:event_division_comboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N1000T;
    private javax.swing.JTextField N100T;
    private javax.swing.JTextField N10T;
    private javax.swing.JTextField N2000T;
    private javax.swing.JTextField N20T;
    private javax.swing.JTextField N5000T;
    private javax.swing.JTextField N500T;
    private javax.swing.JTextField N50T;
    private javax.swing.JTextField basicPay10;
    private javax.swing.JTextField basicPay11;
    private javax.swing.JTextField basicPay8;
    private javax.swing.JComboBox checkrollOrStaff;
    private javax.swing.JPanel division;
    private javax.swing.JComboBox division_combo;
    private javax.swing.JTextField fullPay;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField month;
    private javax.swing.JComboBox register_or_casual_combo;
    private javax.swing.JTextField total;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
