
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pramo
 */
public class PRCR_salary_payroll extends javax.swing.JPanel {

    /**
     * Creates new form PRCR_salary_payroll
     */
    Payroll_Salary spiObject = new Payroll_Salary();
    Date_Handler datehandler = new Date_Handler();
    DatabaseManager dbm = DatabaseManager.getDbCon();

    public PRCR_salary_payroll() {
        initComponents();
    }

    public String[] combo() {
        int count = 0;
        try {
            ResultSet query = dbm.query("SELECT * FROM personal_info WHERE checkroll_or_staff LIKE '" + "Staff" + "'");
            while (query.next()) {
                count++;
            }
            query.close();
        } catch (SQLException ex) {
            Logger.getLogger(PRCR_salary_payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        String arr[] = new String[count + 1];
        arr[0] = "";
        count = 1;
        try {
            ResultSet query = dbm.query("SELECT * FROM personal_info WHERE checkroll_or_staff LIKE '" + "Staff" + "'");
            while (query.next()) {
                arr[count] = query.getString("code");
                count++;
            }
            query.close();
        } catch (SQLException ex) {
            Logger.getLogger(PRCR_salary_payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        return arr;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        code = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        incentive1 = new javax.swing.JTextField();
        basic_sallary = new javax.swing.JTextField();
        ot_rate = new javax.swing.JTextField();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Employee Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        name.setBackground(new java.awt.Color(204, 204, 204));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        code.setEditable(true);
        DatabaseManager dbm=DatabaseManager.getDbCon();
        code.setModel(new javax.swing.DefaultComboBoxModel(combo()));
        code.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                codeItemStateChanged(evt);
            }
        });
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeFocusLost(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Basic Salary");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Incentive 1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("OT Rate");

        incentive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incentive1ActionPerformed(evt);
            }
        });

        basic_sallary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_sallaryActionPerformed(evt);
            }
        });

        ot_rate.setEditable(false);
        ot_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ot_rateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(basic_sallary, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(incentive1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ot_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basic_sallary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ot_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incentive1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_codeActionPerformed

    private void codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_codeFocusLost
    MessageBox msg = new MessageBox();
    Check_Entries chk = new Check_Entries();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (chk.isDouble(incentive1.getText()) && chk.isDouble(basic_sallary.getText())) {
            try {
                dbm.CheckNDeleteFromDataBase("prcr_payroll_incentive", "emp_code", Integer.parseInt(code.getSelectedItem().toString()));
            } catch (Exception ex) {

            }
            int empCode = Integer.parseInt(code.getSelectedItem().toString());
            double incentive = Double.parseDouble(incentive1.getText());
            double baasic = Double.parseDouble(basic_sallary.getText());
            try {
                dbm.insert("INSERT INTO prcr_payroll_incentive (emp_code,incentive) VALUES('" + empCode + "','" + incentive + "')");
            } catch (SQLException ex) {
                Logger.getLogger(PRCR_salary_payroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            dbm.updateDatabase("personal_info", "code", empCode, "basic_salary", baasic);
            name.setText(null);
            basic_sallary.setText(null);
            ot_rate.setText(null);
            incentive1.setText(null);
            code.setSelectedIndex(0);
            code.requestFocus();
        } else {
            msg.showMessage("Entered Amounts are not Valid. Please check again", "Salary Details", "info");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codeItemStateChanged

        String Name = null;
        double basic_salary = 0;
        double incentive = 0;
        double ot_raten = 0;
        int item = 0;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                item = Integer.parseInt(evt.getItem().toString());
            } catch (Exception ex) {
            }

            try {
                ResultSet query = dbm.query("SELECT * FROM personal_info WHERE code LIKE " + item + "");
                while (query.next()) {
                    Name = query.getString("name");
                    basic_salary = query.getDouble("basic_salary");
                }
                query.close();
            } catch (SQLException ex) {
            }

            try {
                ResultSet query = dbm.query("SELECT * FROM prcr_payroll_incentive WHERE emp_code LIKE " + item + "");
                while (query.next()) {
                    incentive = query.getDouble("incentive");
                }
                query.close();
            } catch (SQLException ex) {
                incentive = 0;
            }

            ot_raten = Math.ceil((basic_salary / 240 * 1.5) * 100.0) / 100.0;
            name.setText(Name);
            basic_sallary.setText("" + basic_salary);
            incentive1.setText("" + incentive);
            ot_rate.setText("" + ot_raten);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_codeItemStateChanged

    private void incentive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incentive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incentive1ActionPerformed

    private void basic_sallaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_sallaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic_sallaryActionPerformed

    private void ot_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ot_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ot_rateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basic_sallary;
    private javax.swing.JComboBox code;
    private javax.swing.JTextField incentive1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ot_rate;
    // End of variables declaration//GEN-END:variables
}
